FROM resin/rpi-raspbian

ENV INITSYSTEM on

RUN apt-get -q update && apt-get install -yq --no-install-recommends \
	build-essential curl file \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get install -qq

WORKDIR /usr/src/app

RUN curl -sSf https://static.rust-lang.org/rustup.sh | sh

COPY . /usr/src/app

RUN uname -a

RUN cargo run

CMD ./target/debug/resin-rust-hello-world